services:
  - type: web
    name: giantogram-tiktok-frontend
    env: static
    buildCommand: |
      cd frontend &&
      rm -rf node_modules &&
      npm cache clean --force &&
      npm install &&
      NODE_ENV=production npx vite build
    staticPublishPath: frontend/build
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /static/*
        destination: /static/*
      - type: rewrite
        source: /assets/*
        destination: /assets/*
      - type: rewrite
        source: /*
        destination: /index.html
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://giantogram-tiktok.onrender.com
